
# .streamlit/secrets.toml

# Gmail credentials for password reset (use an App Password)
EMAIL_ADDRESS = "saaondoterkuma@gmail.com"
EMAIL_PASSWORD = "your_app_password_here"

# Google OAuth credentials
GOOGLE_CLIENT_ID = "your_google_client_id_here"
GOOGLE_CLIENT_SECRET = "your_google_client_secret_here"
